spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    username: app_user
    password: password
    url: jdbc:postgresql://localhost:5432/chat_application
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: chat.app.ie213@gmail.com
    password: ukfnyfqglbbwshqp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  access:
    duration: 3600
  refresh:
    duration: 3600
  secret: my-super-strong-powerful-charming-and-lovely-secret-1DW*(#$Pf42fDS23

app:
  message-modifiability-duration: 5
  storage-location: /home/martiandreamer/chat_application