spring:
  datasource:
    username: app_user
    password: password
    url: jdbc:postgresql://localhost:5432/chat_application
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  access:
    duration: 20
  refresh:
    duration: 2
  secret: my-super-strong-powerful-charming-and-lovely-secret-1DW*(#$Pf42fDS23