spring:
  datasource:
    username: app_user
    password: password
    url: jdbc:postgresql://localhost:5432/chat_application
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    mongodb:
      host: localhost
      port: 27017
      username: app_user
      password: password
      authentication-database: chat_application
      auto-index-creation: true
