spring:
  datasource:
    username: app_user
    password: password
    url: jdbc:postgresql://localhost:5432/chat_application
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true